INSERT INTO [R_Career.am].[dbo].[Industries] (Name)
	VALUES
    ('Software development'),
    ('Quality Assurance /Control'),
    ('UI/UX/Graphic Design'),
	('Product/Project Management'),
	('Hardware design'),
	('Other IT'),
	('Sales/service management'),
	('Administrative/office-work'),
	('Tourism/Hospitality/HoReCa'),
	('Marketing/Advertising'),
	('Communications/Journalism/PR'),
	('Accounting/Bookkeeping/Cash register'),
	('Finance Management'),
	('Banking/credit'),
	('TV/Radio'),
	('Education/training'),
	('Legal'),
	('Audit/Compliance'),
	('Healthcare/Pharmaceutical'),
	('Construction'),
	('Human Resources'),
	('Sports/Beauty'),
	('Procurement/Logistics/Courier'),
	('Production'),
	('Business/Management'),
	('Art/Design/Architecture'),
	('General/professional/Other services'),
	('IT security/Networks'),
	('NGO/Nonprofit'),
	('NGO/Nonprofit'),
	('Entertainment'),
	('Data Science/Data Engineering'),
	('Foreign language'),
	('Economics'),
	('Hardware Design / Engineering'),
	('Data Research/Analysis'),
	('Mechanical/Engineering'),
	('System Admin/Engineer'),
	('Retail business'),
	('Network Administration'),
	('Consultancy'),
	('State/ Public/ Civil service'),
	('Science'),
	('Content writing'),
	('Security'),
	('Aviation'),
	('DevOps/Infrastructure '),
	('IT Support/Technician');